export const setColors = {
    white: '#FFFFFF',
    black: '#000000',
    gray: 'gray',
    violetShade: '#473F97',
    grayShade: '#EAECEF',
    darkgrayShade: '#C4C4C4',
    lightWhite: '#A6A2CC',
    errorRed: 'red',
    dashCompBackground: '#E9F9F5',
    calendarRed: '#F53567',
    calImpColor: '#FEF1EC',
    backgroundGreen: '#37B264',
    calImpGreenColor: '#D4FFEA',
    blueShade: '#d2f4fe',
    pinkShade: '#FEF1EC',
    statusRed: '#F53567',
    pinkShade: '#EEE5FF',
    violetLightShade: '#D4FFEA',
    calendarBlue: '#3924E8',
    calendarEvent: '#24E8B6',
    sudokuError: '#FD582D',
    sudokuLightShade: '#CDCBF0',
    defaultSudokuTxt: '#2116de'
}